# executable configurations

port: 4444
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# global data configurations

name: Corey Caskey
job_description: Software Engineer
email: coreyrcaskey@gmail.com
title: Corey Caskey | Personal Website
description: Hi! Welcome to my personal website. My name is Corey Caskey, and I am a Software Engineer.
