name: Corey Caskey
job_description: Software Engineer
email: coreyrcaskey@gmail.com
title: Corey Caskey | Personal Website
description: Hi! Welcome to my personal website. My name is Corey Caskey, and I am a Software Engineer.

github: https://github.com/ccaskey06
linkedin: https://www.linkedin.com/in/caskeycorey/
instagram: https://www.instagram.com/coreycaskey/
resume: ../assets/resume.pdf

intro: Hi, my name is Corey Caskey. I am a Software Engineer at Capital One. I
  joined the company as part of an entry-level rotational program and have
  had experiences across the entire stack. And only recently have I
  decided to pursue a focused career path in Frontend Engineering.

port: 4444
